### ISSUE TITLE
Using the code for WRSC 2018

### ISSUE THREAD

**Issue by takluyver** [nicolas2lee/AdvancedMYR#2]
Hello! We're hoping to use the tracking system again for WRSC 2018, and I had a couple of questions about it:

- Is *AdvancedMYR* newer than the project called [WRSCMonitor](https://github.com/SylvainHunault/WRSCMonitor) ?
- The most recently updated version of the code I can find is the [WRSC2016 branch](https://github.com/SylvainHunault/AdvancedMYR/tree/WRSC2016) of @SylvainHunault's fork. Is that the best version to start with?
- How do we run it to test? I'm not used to Ruby, so I don't know what the magic command to make it go is. ;-)
- I'm planning to set up a WRSC organisation on Github to host this code, along with any other relevant stuff. I'm happy to invite any of you to join that organisation (cc @SylvainHunault @olivierreynet).

Thanks!

**Comment by nicolas2lee** [comment]
To answer your @takluyver questions:

##  - Is AdvancedMYR newer than the project called WRSCMonitor ?
_It has been a long time that I did not work on it. I am not sure, but probably it is newer than WRSCMonitor._

## - The most recently updated version of the code I can find is the WRSC2016 branch of @SylvainHunault's fork. Is that the best version to start with?
_This project is for WRSC2015, I did not participate the development of WRSC2016, so I cannot answer this question. In my opinion, it is a good idea to start with @SylvainHunault's fork, but you should ask @SylvainHunault ._

## - How do we run it to test? I'm not used to Ruby, so I don't know what the magic command to make it go is. ;-)
_Good question, I am a java developer now, but I guess it is `rake test`. It is a good idea to keep TDD, BDD, DDD in mind_

## - I'm planning to set up a WRSC organisation on Github to host this code, along with any other relevant stuff. I'm happy to invite any of you to join that organisation (cc @SylvainHunault @olivierreynet).
_No problem for me, you can host this code. But you must ask @olivierreynet and ENSTA Bretagne before hosting and migrating the code._


What's more. I am glad if I can join the organization. Although I rarely use ruby on rails for web projects now, I think I have a lot of ideas for improving this project. Also if it is possible, I can join the development as my part time job (sure it is free, just for fun), since I have my work to do.
Here are some tips in my mind:
- use web socket instead of REST api for sending data, or even maybe rxRuby
- setup docker jenkins sonar for auto deployment
- maybe isolation of front & back end (like angularjs or reactjs for front, since the js stack is better for front end stuff in my experience, ruby on rails for back end)

**Comment by takluyver** [comment]
Thanks, I'll happily add you to the organisation as and when it's set up, and any help improving the appliciation will be welcome.

Good point about getting permission. Another question for everyone who's been involved in writing this code: I don't think there's currently a license associated with this code? Sorry if there is and I've missed it. Could you agree on one? If you're not sure where to start, [choosealicense.com](https://choosealicense.com/) is a good place.

**Comment by ghost** [comment]
Hello,
this code should be placed under the simplest license, eg https://creativecommons.org/licenses/by/4.0/.
People who should be named are (at least) :
- Quentin Descours
- Sylvain Hunault
- Tao Zheng
Best regards,
Olivier

**Comment by takluyver** [comment]
Thanks Olivier!

The CC licenses are not usually used for code. Would you be happy with the [MIT license](https://opensource.org/licenses/MIT), which is similar in spirit to CC-BY? That's also the license that we're using for our own robot code.

**Comment by ghost** [comment]
yes, it was an example. 


De: "Thomas Kluyver" <notifications@github.com> 
À: "nicolas2lee/AdvancedMYR" <AdvancedMYR@noreply.github.com> 
Cc: "Olivier Reynet" <olivier.reynet@ensta-bretagne.fr>, "Mention" <mention@noreply.github.com> 
Envoyé: Jeudi 18 Janvier 2018 16:38:46 
Objet: Re: [nicolas2lee/AdvancedMYR] Using the code for WRSC 2018 (#2) 



Thanks Olivier! 

The CC licenses are not usually used for code. Would you be happy with the [ https://opensource.org/licenses/MIT | MIT license ] , which is similar in spirit to CC-BY? That's also the license that we're using for our own robot code.

**Comment by takluyver** [comment]
Great, thanks!

@nicolas2lee @SylvainHunault are you also happy for it to be under the MIT license? Does someone want to check with Quentin Descours? I don't know his Github username to ping him.

**Comment by chinchifou** [comment]
Hello Thomas,

Nice to hear that you intend to use our code !

My name is Benoit BOURDON (github <https://github.com/chinchifou>), I
worked on this project with Bastien DROUOT (github
<https://github.com/Sylyon>) between 2014 and 2015.
I mostly worked on the Ruby on Rails server (code base and optimization)
and GUI while Bastien worked on the tracker, server authentication and
website generation.
Sylvain and Tao have then improved the website for the WRSC 2015 and 2016.

I am happy to share with you all the documentation that I am aware of:
SWARMON (first phase 2014 - FR )
<https://drive.google.com/open?id=0BzhajQ_FFJg_UEY3VlUzZjd4STQ>
Monitor Your Robot (Second phase 2015 - EN)
<https://drive.google.com/open?id=0BzhajQ_FFJg_dWlqV3hTSm5teWM>
IRSC 2015 (article and presentation - EN)
<https://drive.google.com/open?id=0BzhajQ_FFJg_Vld0a2N5ekYzajg> (especially
useful to have a quick overview of the whole project)

To answer your questions :

- for the versioning, as I did not work on the latest phases, I am a bit
lost but Tao assumption makes sense.
- for testing I think you have to use rake test but to be fair, except to
populate the database, at the time I did not write any test case. :/
- I am fine with an MIT license. Could you name me and Bastien as well
please ? (I am pretty sure that Bastien would be OK with a beerware
license, so an MIT license should also do the trick :) )

As I am know a full time engineer I will not have much time to help you
with the code but would be happy to help if you are stuck during the
development.

Best regards,

Benoit BOURDON


2018-01-18 18:06 GMT+01:00 Thomas Kluyver <notifications@github.com>:

**Comment by takluyver** [comment]
Thanks Benoit! I'll have a look over those materials.

So would this copyright line be OK:

> Copyright 2014-2016 Benoit Bourdon, Bastien Druout, Olivier Reynet, Sylvain Hunault, Zheng Tao, Quentin Descours and contributors

So far, everyone who's commented seems to be happy with the MIT license. I'll give it another week for the other people who worked on it to chime in; after that, if there are no objections, I'll apply the MIT license.

**Comment by chinchifou** [comment]
Perfect!

2018-01-22 11:34 GMT+01:00 Thomas Kluyver <notifications@github.com>:

**Comment by takluyver** [comment]
I have added the MIT license - with the copyright line from my previous message - to our new copy of the repo at https://github.com/WRSC/tracking . Thanks everyone!

**Comment by SylvainHunault** [comment]
Hi everyone,


I am glad to see some movements around the project.


As Benoit, I have a full time engineer job now and I am very busy. I'll try to help as much as I can.


For the licence, there is no problem for the MIT one.


Regards.


Sylvain HUNAULT
Ingénieur ENSTA Bretagne
Option SPID - Profil Robotique & Systèmes Embarqués
Promotion 2016
Ingénieur Systèmes Embarqués à RUAG Defence France (Albi)
________________________________
De : Benoit Bourdon <notifications@github.com>
Envoyé : lundi 22 janvier 2018 19:56:56
À : nicolas2lee/AdvancedMYR
Cc : Sylvain HUNAULT (CI2016); Mention
Objet : Re: [nicolas2lee/AdvancedMYR] Using the code for WRSC 2018 (#2)

Perfect!

2018-01-22 11:34 GMT+01:00 Thomas Kluyver <notifications@github.com>:

**Comment by takluyver** [comment]
Thanks Sylvain!
